### ISSUE TITLE
there seems to be a little glitch when chart is minimized and then maximized

### ISSUE THREAD

**Issue by ksobon** [tt-acm/DesignExplorer#100]
![image](https://user-images.githubusercontent.com/529781/31521581-054cd4aa-af78-11e7-874c-0c83bc6e56bc.png)

This happens after chart is collapsed, and then re-opened.

**Comment by MingboPeng** [comment]
@ksobon it is weird.  I couldn't recreate this issue. 
Do you mean this button?
![image](https://user-images.githubusercontent.com/9031066/31639639-c3673e08-b2a7-11e7-93ed-0d8b1ff365f7.png)

**Comment by ksobon** [comment]
Yeah it happens pretty consistently. First hide the scatter plots with this button: 

![image](https://user-images.githubusercontent.com/529781/31640666-acb9cfc6-b2ad-11e7-84ca-add8b9667a7f.png)

Then toggle the parallel coordinates with this: 

![image](https://user-images.githubusercontent.com/529781/31640686-c62cc288-b2ad-11e7-9c73-4b0e36cf3ad1.png)

It should give you what I posted about.

**Comment by MingboPeng** [comment]
@ksobon  thanks, fixed. 8412852658071831f52158effb52eb1d8d7b7ad9
