### ISSUE TITLE
Design Explorer does not load the data generated from the GH example files (in Rhino 6)

### ISSUE THREAD

**Issue by MarleenAndela** [tt-acm/DesignExplorer#106]
Design Explorer does not load the data generated from the GH example files (in Rhino 6). It says: Could not find the data.csv file in this folder, please double check! The same happens when I upload a .zip file. All the files are there so I am a bit clueless about what could be wrong. I really hope someone can help me out because I'd love to give it a try. 

Thanks in advance!

**Comment by mostaphaRoudsari** [comment]
Are you sure that you are using the link to the folder itself? Can you share the link with us?

**Comment by MarleenAndela** [comment]
Hi, thanks for the quick reply. I did indeed not supply the right link, thanks for pointing that out. It is working now!

**Comment by mostaphaRoudsari** [comment]
Perfect! Thank you for letting me know.
