### ISSUE TITLE
Platypus "time's up partner" error message

### ISSUE THREAD

**Issue by MarleenAndela** [tt-acm/DesignExplorer#107]
Hi,
I would like to try Platypus, but the Platypus connect component is giving the following error: "Time's up partner, Head over to Food4Rhino to download some updated components, or visit core.thorntontomassetti.com for more information" 
I am using Rhino 6 on Windows and I downloaded the latest version of TT Toolbox.
What could be going wrong? 

Thanks in advance!

**Comment by mostaphaRoudsari** [comment]
Hi @MarleenAndela, This repository is for DesignExplorer. You should post this issue to Food4Rhino or Grasshopper Forum: https://www.grasshopper3d.com/group/corestudio
I'm not sure if Platypus development is supported anymore but @bhowes-tt should know.

**Comment by bhowes-tt** [comment]
Thanks for the ping @mostaphaRoudsari , and thanks @MarleenAndela for asking.  Platypus is indeed out of date and we have not released an update.  We've been hesitant to kill the project outright, but we're probably done supporting the alpha at this point, too.
