### ISSUE TITLE
2D / 3D file hosting

### ISSUE THREAD

**Issue by mnaugle-tt** [tt-acm/DesignExplorer#64]
This is a bit of a sticky point in the current build.  

As a recap:
In our build now, a user provides a CSV at the time of populating the Design Explorer interface.  That CSV has all of the input and output data along with links to the 2D and 3D files that belong to that design iteration.  Those 2D and 3D files most be hosted prior to populating the interface.  We had been using dropbox for hosting because it allows for URLs that match a folder structure and the name of the file itself.  This means you can quickly modify the CSV to match your URLs since only the name of the image or 3D json will change.

For example dropbox allows for URLs that look like this:
https://dl.dropboxusercontent.com/u/SOME_ID_Specific_To_The_User/MyFolder1/MyFolder2/MyImage1.jpg

Unfortunately dropbox only allows this folder structure as a URL for Pro users or users that created their dropbox before 2013.  https://www.dropbox.com/en/help/16  This means most people will need to pay to be able to use dropbox for Design Explorer.  Google Drive doesn't appear to give URL matching a folder structure or anything that can easily be created in Excel.

A better solution needs to be found for how to serve anywhere between 10 and 10,000 images and 3D models.  A server is definitely the right solution, looking for ideas on how to make it happen in a more diy/hackable manner too. 

cc @mostaphaRoudsari @bhowes-tt @JonatanS

**Comment by mostaphaRoudsari** [comment]
Can this be the solution:

```
 It’s important to remember that if you drop a file onto Dropbox and want the raw data supported,
you have to change the www.dropbox.com portion of the URL to dl.dropboxusercontent.com.
```

From this page: https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a

**Comment by mnaugle-tt** [comment]
@mostaphaRoudsari --

Are you suggesting to have each spectacles file as raw json in a google spread sheet?

**Comment by mostaphaRoudsari** [comment]
Sorry if I wasn't clear. No. I was hoping that changing dropbox addresses from "www.dropbox.com" to "dl.dropboxusercontent.com" solved the problem that you mentioned above.

**Comment by bhowes-tt** [comment]
I think we should give amazon S3 a try.  I'm pretty sure the url matches the folder structure, and I know you can set up buckets to handle cross-origin requests.  

If we really wanted to get loose with it we could write an uploader for grasshopper too...

**Comment by johnmsloane** [comment]
Hi, I am somewhat of a new user to this Design Explorer world, and have been using Colibri for a bit now (as a student). I was wondering if there was any resolution to this file hosting. I am interested in taking some of the runs I have been creating in Colobri and linking the images to Design Explorer 2. I am not sure if there is a file hosting that is being used that can, like you all said, allow for the naming to be intuitive based on filenames. Any feedback would be appreciated.

**Comment by mostaphaRoudsari** [comment]
This has been resolved by @MingboPeng! You can use either GoogleDrive or Microsoft's OneDrive to upload your models next to the csv file.
