### ISSUE TITLE
User question; CSV format for images

### ISSUE THREAD

**Issue by LudvigHaav** [tt-acm/DesignExplorer#72]
Hi!

I'm having problems getting images to show. I've pasted a CSV, below. When i upload this file the image file web adress is written as column names... :( There are clearly some logic as to what is put where that Im not getting, after numerous tries.

And also: The first column is called "name:Identifier". Why does the "name:"-part of it show? It seems it is reading the names as a standard "in:"

(it would be nice with an example .CSV like the one posted for Pollinator - it makes you understand the format very quickly)

[DEtest3.xlsx](https://github.com/tt-acm/DesignExplorer/files/292373/DEtest3.xlsx)

Thanks for what seems to be a great and useful tool!

**Comment by mostaphaRoudsari** [comment]
Hi @LudvigHaav! You can find three example files [here](https://github.com/tt-acm/DesignExplorer/tree/gh-pages/design_explorer_data). Let me know if it solves the problem.

**Comment by mostaphaRoudsari** [comment]
I took a look and the issue is the header _img:rendering_ which should be _img_. This file works for me.
[DEtest3_DE.TXT](https://github.com/tt-acm/DesignExplorer/files/292427/DEtest3_DE.TXT). Change .txt to .csv

![image](https://cloud.githubusercontent.com/assets/2915573/15694770/97b00b20-276e-11e6-8867-387461c05c9e.png)

**Comment by mostaphaRoudsari** [comment]
Also for future reference [here](https://github.com/tt-acm/DesignExplorer/wiki/File-Preparation) is a nice read for file preparation.

**Comment by LudvigHaav** [comment]
Thanks Mostapha!

So all along it was the extra colon ":" that I was using that was causing problems. I took the liberty to edit and remove the colon from "image:" and "threeD" on the file preparation page as to not confuse future users. I hope there is not some other reason for it being there.

My understanding of it after reading the reference page, was that what came after the colon indicated what is being displayed in the interface. In the "name:" tag whatever i write after the colon, for example "identifier" shows as "name:identifier". Can you wirte something after the colon there? Should I write a colon after name?...Im still a bit confused i guess but now that its working for me these bumps are of minor importance. :)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @LudvigHaav ,

I have run the fixed file from this issue through the design explorer and I still get the img column:
https://github.com/tt-acm/DesignExplorer/issues/75

-Chris
