### ISSUE TITLE
User question; JSON files not loading

### ISSUE THREAD

**Issue by LudvigHaav** [tt-acm/DesignExplorer#73]
Hi again,

Im having trouble getting my JSON files to read inside Design Explorer. It freezes in the stage shown in the screenshot below.
![skarmavbild 2016-06-03 kl 00 41 03](https://cloud.githubusercontent.com/assets/19675911/15763957/8b20c7b8-2927-11e6-95f9-16f44f372cd4.png)

I have made sure that the files work fine in the spectacles web viewer.

I have tried to make the geometries i use for testing this as dead simple as i can. The .Jsons are located here: [http://privat.bahnhof.se/wb172264/designexplorer/threeD/](url)

I made them using this setup shown below, with and without a saved view:
![skarmavbild 2016-06-03 kl 01 13 36](https://cloud.githubusercontent.com/assets/19675911/15764103/ad878e44-2928-11e6-9ba4-972d6d27b4a3.png)

My .csv file is attached below as a .txt.
[three.txt](https://github.com/tt-acm/DesignExplorer/files/296673/three.txt)

What could be causing this? Any ideas are much appreciated! :)

**Comment by mostaphaRoudsari** [comment]
@LudvigHaav I tried to open one your json files in [Spectacles viewer](http://core.thorntontomasetti.com/apps/Spectacles/Viewer/) and here is the error that I get:

``` javascript
XMLHttpRequest cannot load http://privat.bahnhof.se/wb172264/designexplorer/threeD/S00101525000025151005251588888888.json.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://core.thorntontomasetti.com' is therefore not allowed access.

SPECTACLES.js:495 Spectacles could not get a json file from the URL you provided
- this is probably a security thing on the json file host's end.
```

You should submit this issue in [Spectacles web viewer](https://github.com/tt-acm/Spectacles.WebViewer/issues) repository.

I think it's happening because files are uploaded to a http and not a http_s_ and Spectacles only supports secure URLs. @anagpuyol, @bhowes-tt can you confirm?

**Comment by bhowes-tt** [comment]
@LudvigHaav only certain webservers will allow access to resources (like your json files) when they are requested from another domain, and they have to be configured to do so.  You can set up an Amazon S3 bucket to allow this type of access, for example.

**Comment by MingboPeng** [comment]
@mostaphaRoudsari  I have found a method to fix this problem by using the same google drive. I will make a tutorial video soon.

**Comment by mostaphaRoudsari** [comment]
@MingboPeng of course you did! :) I'm looking forward to your video.
