### ISSUE TITLE
Seeming Bug in CSV parsing for Images

### ISSUE THREAD

**Issue by chriswmackey** [tt-acm/DesignExplorer#75]
@mostaphaRoudsari and @LudvigHaav ,

I have been trying for the last 3 hours to get the img column that you originally reported on to go away but to no avail.  I have fully read this issue: https://github.com/tt-acm/DesignExplorer/issues/72 and I have even tried running the file that was supposed to be fixed and I get the following:
![image](https://cloud.githubusercontent.com/assets/5567574/17237069/2591b558-551c-11e6-89c4-3e7b3fe06226.png)

Is it possible that this may be a bug?  Here is another file that I have been trying to run with no success.
https://www.dropbox.com/s/1534zscof4c22ew/InitialEnvelopeTest_Struct.csv?dl=0

Thank you!
-Chris

**Comment by chriswmackey** [comment]
I just updated to @MingboPeng 's new version but there are still some issues.  For some reason, only one image loads and not all of those that are referenced.  You can see this by using the file that I posted.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey your file loads on my machine with no issues but even if the axis shows up you can hide it from the side bar. Click on the arrow on the top-left to hide/unhide the bar.

![image](https://cloud.githubusercontent.com/assets/2915573/17241049/1b78879c-553d-11e6-8744-747ce255ae9f.png)

**Comment by MingboPeng** [comment]
@chriswmackey  Hi Chris, I have no problem to load your data, but it seems all your images are the same.

**Comment by chriswmackey** [comment]
@MingboPeng and @mostaphaRoudsari ,

Thanks for the response.  @MingboPeng , with your new version the img column goes away so that bug appears to be fixed.  However, you can see in the csv and my dropbox that not all of the images are the same.  It appears to be a bug in the workflow for using images from dropbox links.

I eventually got it to work by using the new google drive method as you can see here:
http://tt-acm.github.io/DesignExplorer/?GFOLDER=0Bz2PwDvkjovJaXVhallnemQyYU0

I'll use this method here on out but it might be a good idea to fix the dropbox workflow.
-Chris

**Comment by MingboPeng** [comment]
@chriswmackey  Good to hear that Google Drive method works for you. 
Sure, I will take a look for the dropbox.

**Comment by chriswmackey** [comment]
Thanks @mingbopeng ,
We should have closed this a long time ago. I (and I think most people) have really only been using the Google drive version so I wouldn't worry about the Dropbox issue I had.
