### ISSUE TITLE
Google Drive Access

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/DesignExplorer#76]
@MingboPeng - looks like something isn't working with Google Drive access...  Examples that worked a few weeks back (right after we accepted the pull) no longer do.  I tried a fresh example today, too ,and that didn't work either.

Can you please have a look and verify that something is wrong?

**Comment by MingboPeng** [comment]
@bhowes-tt - you are right, it seems google closed the direct access to Google Drive, I will see if there is any alternative.

**Comment by bhowes-tt** [comment]
Thanks @MingboPeng - glad it's not just me!   Keep us posted.

**Comment by MingboPeng** [comment]
@bhowes-tt - it has been fixed with a temporary solution, please merge.

**Comment by bhowes-tt** [comment]
You rock @MingboPeng !   :loud_sound: :guitar: :loud_sound: 

I'll review in the AM.

**Comment by chriswmackey** [comment]
@MingboPeng and @bhowes-tt ,

I recently encountered this issue today.  Did the temporary solution fix the issue or is it possible that it might occur again?

-Chris

**Comment by bhowes-tt** [comment]
@chriswmackey - Mingbo has a patch on his fork, and has submitted a pull.

@MingboPeng - can we discuss at TT tomorrow?  I had a couple of questions 25 days ago ... I didn't have much time to review and I bet a quick discussion would save a bunch of time!  I'll come find you upstairs...

Thanks for the reminder @chriswmackey !!! :boat:

**Comment by chriswmackey** [comment]
Thank YOU for the support @bhowes-tt !  Looking forward to the patch.

**Comment by MingboPeng** [comment]
@chriswmackey , Hi Chris, Google Drive closed its sharing policy for public hosting, and it is hard to get files directly from Google Drive. But I have found an other way to get files from google drive. Just fixed it, and I will do some test tomorrow.

**Comment by chriswmackey** [comment]
Awesome. Thank-you, @MingboPeng !

**Comment by nickrekstad** [comment]
@MingboPeng, I am definitely looking forward to seeing the fix rolled out. We have been using Design Explorer a lot at Arup and it would save a ton of time to be able to simply drop everything in Google Drive again. Your efforts are very appreciated!

**Comment by MingboPeng** [comment]
@nickrekstad Hi Nick, happy to hear you are using DE, and Google Drive makes easier for you as well. I have fixed it last week, and now you can use it again. 
(Now Google Drive limits user only have 10,000 requests per 100s, just let you know if DE can only load partial images, and please just wait 100s)

**Comment by bhowes-tt** [comment]
Working again!!!  I just merged pull #77 from @MingboPeng 

:guitar: :speaker:

**Comment by chriswmackey** [comment]
Woohoo!

Thank you @mingbopeng and @bhowes-tt ! I will check out the fix soon.

-Chris

**Comment by nickrekstad** [comment]
Works great! Thank you @MingboPeng  and @bhowes-tt.
