### ISSUE TITLE
Static Links using servers other than Google

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/DesignExplorer#78]
@MingboPeng I was able to set up an S3 bucket to serve data, and everything (data, images, spectacles.json files) worked beautifully when using the 'Get Data' button to point to the bucket.  Very awesome!

But, when trying a open a static link, everything goes haywire:
![image](https://cloud.githubusercontent.com/assets/3171551/17992527/2a3cdbe0-6b16-11e6-9303-9656342b3b34.png)

I can email you the bucket's URL if you'd like it to debug.  It's for a project so I can't share publicly.

**Comment by MingboPeng** [comment]
@bhowes-tt , sure, please send me the link, and I can test it!

**Comment by bhowes-tt** [comment]
Sent you an email to your TT address.  THANKS!

**Comment by MingboPeng** [comment]
@bhowes-tt - It was my mistake, now fixed with both Google Drive and server.

**Comment by bhowes-tt** [comment]
Working again!  Thanks @MingboPeng
