### ISSUE TITLE
New Design Explorer is Amazing but Attributes Pane is Blocking Content

### ISSUE THREAD

**Issue by chriswmackey** [tt-acm/DesignExplorer#97]
@MingboPeng ,

I can't begin to tell you how impressed I am with the new Design Explorer and the most recent version of Colibri.  By improving and maintaining these tools, you have truly advanced the profession.

I have only one (very small) suggestion and this is that the new attributes pane is blocking a lot of the content that people want to visualize in the explorer:
![image](https://user-images.githubusercontent.com/5567574/28441945-813ebb3a-6d7b-11e7-93a9-0ad8a730c52d.png)

I am finding myself making images with a lot of white space to the left just to avoid this case of content not being visible.  I feel that the tool would be better without the attributes pane or with an optional attribute pane that slides out.  Or perhaps there's presently a way to make it disappear that I am missing?

Thank you, again, as always.

**Comment by MingboPeng** [comment]
@chriswmackey I am so glad that you tried. Yes, that panel was meant to be moveable and hideable, but I never got time to keep working on that since last update. But it will be updated. Thanks again for your comments

**Comment by chriswmackey** [comment]
Thanks again @mingbopeng ,

Glad to hear that moveability if the panel is on the agenda

**Comment by MingboPeng** [comment]
@chriswmackey added Collapsible body

**Comment by chriswmackey** [comment]
Wonderful. Thanks @mingbopeng !
